#version 330 compatibility

/* RENDERTARGETS: 0,1,2 */
// 0 final color, 1 final normal, 2 pbr stuffs

// --- Uniforms ---
// Textures provided by the shader pipeline
uniform sampler2D lightmap;      // Minecraft's internal lightmap (block and sky light)
uniform sampler2D gtexture;      // The base block texture
uniform sampler2D normals;       // Normal map (if PBR is used)
uniform sampler2D specular;      // Specular map (if PBR is used)
uniform sampler2D shadowtex0;    // The depth map generated by the shadow pass

// Matrices and vectors for coordinate transformation and lighting
uniform mat4 shadowModelView;
uniform mat4 shadowProjection;
uniform vec3 shadowLightPosition; // Position of the sun or moon in view space
uniform float alphaTestRef = 0.1;  // Threshold for discarding transparent fragments
uniform int worldTime;            // Current Minecraft time (0-24000)
uniform vec3 cameraPosition; 
uniform vec4 entityColor;         // Used for "red flash" when mobs take damage

// --- Inputs from Vertex Shader ---
in vec2 lmcoord;     // Lightmap coordinates
in vec2 texcoord;    // Texture coordinates
in vec3 normal;      // Fragment normal in view space
in vec3 binormal;    // Binormal for normal mapping
in vec3 tangent;     // Tangent for normal mapping
in vec4 glcolor;     // Vertex color (biome tinting, etc.)
in vec3 viewVector;  // Vector from camera to fragment
in vec3 worldPos;    // Fragment position in world space

// --- Constants ---
// Environmental light colors defined for different times of day
const vec3 MOON_BLUE  = vec3(0.3, 0.35, 0.45) * 0.85;
const vec3 SUNRISE    = vec3(1.0, 0.5, 0.3) * 0.5;
const vec3 NOON       = vec3(0.95, 0.98, 1.0) * 1.0;
const vec3 SUNSET     = vec3(0.5, 0.3, 0.1) * 0.75;

// --- Helper Functions ---
// Placeholder for shadow sampling logic
float getShadow(float NdotL) {
   return float (1.0);
}

// Calculates the sunlight/moonlight color based on the current world time
vec3 calcLightColor() {
    float timeFloat = float(worldTime);
    float blendFactor = 0.0;
    vec3 lightColor = MOON_BLUE;

    // Transitions between different times of day using smoothstep for gradual blending
    if (worldTime >= 22000) {
        blendFactor = smoothstep(22000.0, 24000.0, timeFloat);
        lightColor = mix(MOON_BLUE, SUNRISE, blendFactor);
    } else if (worldTime < 1000) {
         blendFactor = smoothstep(0.0, 1000.0, timeFloat);
        lightColor = mix(SUNRISE, NOON, blendFactor);
    } else if (worldTime >= 1000 && worldTime < 6000) {
        blendFactor = smoothstep(1000.0, 6000.0, timeFloat);
        lightColor = mix(mix(SUNRISE, NOON, 0.5), NOON, blendFactor);
    } else if (worldTime >= 6000 && worldTime < 9000) {
        lightColor = NOON;
    } else if (worldTime >= 9000 && worldTime < 12000) {
        blendFactor = smoothstep(9000.0, 12000.0, timeFloat);
        lightColor = mix(NOON, SUNSET, blendFactor);
    } else if (worldTime >= 12000 && worldTime < 14000) {
        blendFactor = smoothstep(12000.0, 14000.0, timeFloat);
        lightColor = mix(SUNSET, MOON_BLUE, blendFactor);
    }
    return lightColor;
}

void main() {
    // 1. Texture Sampling: Combine base texture with vertex color (biome tints)
    vec4 albedo = texture(gtexture, texcoord) * glcolor;
    
    // 2. Alpha Test: Discard transparent pixels (e.g., air, gaps in leaves)
    if (albedo.a < alphaTestRef) discard;
    
    // 3. Entity Tint: Apply damage flash or other entity-specific overlays
    albedo.rgb = mix(albedo.rgb, entityColor.rgb, entityColor.a);
    
    // 4. PBR Attributes: Placeholders for physical properties
    float smoothness = 0.0;
    float metalness  = 0.0;
    float emissive   = 0.0; 

    // 5. Directional Vectors: Normalize inputs for lighting math
    vec3 finalNormal = normalize(normal); 
    vec3 lightDir = normalize(shadowLightPosition); // Direction to the sun/moon
    vec3 viewDir = normalize(-viewVector);         // Direction to the camera

    // 6. Diffuse Lighting: Calculate how much light hits the surface based on its angle
    float NdotL = max(dot(finalNormal, lightDir), 0.0);
    
    // 7. Shadows: Retrieve the shadow intensity
    float shadowValue = getShadow(NdotL);
    
    // 8. Surface Shading: Combine diffuse light and shadow for depth
    float sunMix = NdotL * shadowValue;
    float bumpShadow = sunMix * 0.7 + 0.3; // Ensures shadowed areas aren't pitch black

    // 9. Specular Highlight: Calculate "shiny" reflections
    vec3 reflectDir = reflect(-lightDir, finalNormal);
    float specStrength = pow(max(dot(viewDir, reflectDir), 0.0), 16.0); // 16.0 is the shininess factor
    vec3 highlight = vec3(specStrength) * 0.1 * shadowValue; 

    // 10. Environmental Lighting: Calculate sky and block light
    vec3 sunColor = calcLightColor();
    // Block light (e.g., torches) uses the horizontal axis of the lightmap
    vec3 blockLightColor = texture(lightmap, vec2(lmcoord.x, 0.03)).rgb; 
    // Sky light uses the vertical axis and is tinted by the sun/moon color
    vec3 skyLightColor   = texture(lightmap, vec2(0.03, lmcoord.y)).rgb * sunColor * bumpShadow;

    // 11. Final Color: Combine base color (albedo) with all light sources plus highlights
    vec3 finalColor = albedo.rgb * (blockLightColor + skyLightColor) + highlight;

    // 12. Output: Write data to the specified render targets
    gl_FragData[0] = vec4(finalColor, albedo.a);       // Color Buffer
    gl_FragData[1] = vec4(finalNormal, 1.0);           // Normal Buffer
    gl_FragData[2] = vec4(smoothness, metalness, emissive, 1.0); // PBR Buffer
}